"""Auto-generated DASHBOARD.md - your applying dashboard on GitHub.

Regenerated by the watcher (and backfill_jd.py) whenever the tracker
changes. View it on GitHub - tables render nicely on mobile too.
"""
import os
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).parent
DASHBOARD = ROOT / "DASHBOARD.md"

OPEN = ("found",)
IN_PROGRESS = ("applied", "referred", "oa", "interview")
DONE = ("offer", "rejected", "not_fit")


def repo_url(settings=None):
    """Base GitHub URL: from Actions env when running in CI, else from
    settings.repo_url in companies.yaml."""
    repo = os.environ.get("GITHUB_REPOSITORY")
    if repo:
        return f"https://github.com/{repo}"
    return (settings or {}).get("repo_url", "")


def _esc(s):
    return (s or "").replace("|", "/")


def build_dashboard(rows, settings=None):
    base = repo_url(settings)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    open_rows = [r for r in rows if r.get("status") in OPEN]
    prog_rows = [r for r in rows if r.get("status") in IN_PROGRESS]
    done = {s: sum(1 for r in rows if r.get("status") == s) for s in DONE}

    L = [f"# 📋 JobHunt dashboard", "",
         f"_Auto-generated {now} — do not edit (edit tracker.csv instead)._", ""]
    if base:
        L.append(f"Quick links: [tracker.csv]({base}/blob/main/tracker.csv) · "
                 f"[rejected_log.csv]({base}/blob/main/rejected_log.csv) · "
                 f"[contacts.csv]({base}/blob/main/contacts.csv) · "
                 f"[reports/]({base}/tree/main/reports)")
        L.append("")

    L.append(f"## 🎯 To apply ({len(open_rows)})")
    L.append("")
    if open_rows:
        L.append("| found | role | company | apply | after applying, run |")
        L.append("|---|---|---|---|---|")
        for r in sorted(open_rows, key=lambda r: r.get("date_found", ""), reverse=True):
            jid = r["job_url"].rstrip("/").split("/")[-1][:26]
            L.append(f"| {r['date_found']} | {_esc(r['role'])} | {_esc(r['company'])} "
                     f"| [apply ↗]({r['job_url']}) | `python track.py applied {jid}` |")
    else:
        L.append("Nothing pending — the watcher will add new finds here.")
    L.append("")

    L.append(f"## 🚀 In progress ({len(prog_rows)})")
    L.append("")
    if prog_rows:
        L.append("| status | role | company | applied | response | follow-up due |")
        L.append("|---|---|---|---|---|---|")
        for r in sorted(prog_rows, key=lambda r: r.get("applied_date", ""), reverse=True):
            L.append(f"| {r['status']} | [{_esc(r['role'])}]({r['job_url']}) "
                     f"| {_esc(r['company'])} | {r.get('applied_date','')} "
                     f"| {r.get('response','')} | {r.get('followup_due','')} |")
    else:
        L.append("No applications in flight yet.")
    L.append("")

    L.append(f"## 🗄️ Closed: {done.get('offer',0)} offer · "
             f"{done.get('rejected',0)} rejected · "
             f"{done.get('not_fit',0)} filtered out as not-fresher-fit "
             f"(see rejected_log.csv)")
    return "\n".join(L) + "\n"


def write_dashboard(rows, settings=None):
    DASHBOARD.write_text(build_dashboard(rows, settings), encoding="utf-8")
